baseurl: ""
url: "https://oltdaniel.at"
description: >-
    personal page
permalink: :year/:title.html
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
sass:
  style: compressed
highlighter: none
future: true
excerpt_separator: <!--abstract-->
exclude:
  - Gemfile
  - Gemfile.lock
  - pu.sh
  - CNAME